# Generated by Django 4.1 on 2022-10-04 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150, verbose_name='Complete Name')),
                ('address', models.CharField(max_length=150, verbose_name='Complete Address')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('dname', models.CharField(max_length=150, verbose_name='Driver Name/Operator Name')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone Address')),
                ('d_address', models.CharField(max_length=150, verbose_name='Driver/Operator Complete Address')),
                ('plate_number', models.CharField(max_length=50, verbose_name='Plate Number')),
                ('accident_date', models.DateField(verbose_name='Date of Accident')),
                ('accident_time', models.TimeField(verbose_name='Time of Accident')),
                ('accident_place', models.CharField(max_length=150, verbose_name='Place of Accident')),
                ('complaint_description', models.TextField(verbose_name='Complaint Description')),
                ('complaint_evidence', models.ImageField(blank=True, null=True, upload_to='evidences', verbose_name='Evidence Image')),
                ('verification', models.CharField(choices=[('Accept', 'Accept'), ('Reviewing', 'Reviewing'), ('Decline', 'Decline')], max_length=100, verbose_name='Verification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
