# Generated by Django 4.1.2 on 2022-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricyhelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, verbose_name='Complete Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject Message')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150, verbose_name='Complete Name')),
                ('address', models.CharField(max_length=150, verbose_name='Complete Address')),
                ('phone_number', models.CharField(default='+63', max_length=13, verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Profile Picture')),
            ],
        ),
        migrations.AlterField(
            model_name='complaintinformation',
            name='verification',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Reviewing', 'Reviewing'), ('Declined', 'Declined')], max_length=100, verbose_name='Verification'),
        ),
    ]
